// Every photo here was viewed and confirmed before being added — the old
// version was 100% Unsplash stock, which defeats the point of a page whose
// whole job is showing this operator's real photography. A second pass
// (see project history) caught several existing captions that didn't match
// what the photo actually showed (e.g. a buffalo close-up captioned
// "Ngorongoro Crater", a leopard captioned "Crater Floor") — those are
// fixed below. This pass also expanded the set from the original 22 to
// the full range of verified real photography in public/images, including
// the operator's own branded vehicles and guides, not just wildlife.
export const photos = [
  { id: 1, img: '/images/956A3225.webp', caption: 'Lions on the Rocks' },
  { id: 2, img: '/images/956A4243.webp', caption: 'Cape Buffalo Portrait' },
  { id: 3, img: '/images/IMG_2493.webp', caption: 'Maasai Herder and Cattle' },
  { id: 4, img: '/images/956A3919.webp', caption: 'Leopard in the Trees' },
  { id: 5, img: '/images/nakupenda-beach.webp', caption: 'Zanzibar Coastline' },
  { id: 6, img: '/images/956A2874.webp', caption: 'Lion Portrait', featured: true },
  { id: 7, img: '/images/IMG_0227.webp', caption: 'Elephant Herd, Tarangire' },
  { id: 8, img: '/images/stone-town.webp', caption: 'Stone Town, Zanzibar' },
  { id: 9, img: '/images/956A3425.webp', caption: 'Wildebeest Herd' },
  { id: 10, img: '/images/956A3123.webp', caption: 'Cheetahs at Rest' },
  { id: 11, img: '/images/prison.webp', caption: 'An Island off Zanzibar', featured: true },
  { id: 12, img: '/images/956A2025.webp', caption: 'Lioness on the Move' },
  { id: 13, img: '/images/IMG_1256.webp', caption: 'On the Crater Rim' },
  { id: 14, img: '/images/Darajani_Market.jpg', caption: 'Darajani Market, Stone Town' },
  { id: 15, img: '/images/956A1651.webp', caption: 'Warthogs Grazing' },
  { id: 16, img: '/images/956A4274.webp', caption: 'The Great Migration', featured: true },
  { id: 17, img: '/images/956A3701.webp', caption: 'Ostriches on the Plains' },
  { id: 19, img: '/images/956A2358.webp', caption: 'Cheetah Siblings in the Grass' },
  { id: 20, img: '/images/956A3309.webp', caption: 'Our Safari Fleet' },
  { id: 21, img: '/images/956A2613.webp', caption: 'Maasai Herding, Northern Tanzania' },
  { id: 22, img: '/images/956A3279.webp', caption: 'Leopard on the Lookout' },
  { id: 23, img: '/images/956A1471.webp', caption: 'Zebra on the Trail' },
  { id: 24, img: '/images/956A1555.webp', caption: 'Vulture in Flight' },
  { id: 25, img: '/images/956A1564.webp', caption: 'Vultures at the Roost' },
  { id: 26, img: '/images/956A1611.webp', caption: 'Elephant Family by the River' },
  { id: 27, img: '/images/956A1769.webp', caption: 'Leopard at Rest' },
  { id: 28, img: '/images/956A1791_1.webp', caption: 'Leopard by the Water' },
  { id: 29, img: '/images/956A2034.webp', caption: 'Lion Cub Portrait' },
  { id: 30, img: '/images/956A2097.webp', caption: 'Lioness Calling' },
  { id: 31, img: '/images/956A2160.webp', caption: 'Young Lion on the Move' },
  { id: 32, img: '/images/956A2167.webp', caption: 'Lion Cub in Profile' },
  { id: 33, img: '/images/956A2192.webp', caption: 'Marabou Stork' },
  { id: 34, img: '/images/956A2236.webp', caption: 'Lioness Among the Pride' },
  { id: 35, img: '/images/956A2368.webp', caption: 'Cheetah on Alert' },
  { id: 36, img: '/images/956A2527.webp', caption: 'Giraffe Grazing' },
  { id: 37, img: '/images/956A2546.webp', caption: 'Zebra Herd on the Plains' },
  { id: 38, img: '/images/956A2587.webp', caption: 'Elephants on the Move' },
  { id: 39, img: '/images/956A2659.webp', caption: 'Hartebeest on Watch' },
  { id: 40, img: '/images/956A2681.webp', caption: 'Zebra Trio' },
  { id: 41, img: '/images/956A2694.webp', caption: 'Lion in Full Mane' },
  { id: 42, img: '/images/956A2725.webp', caption: 'Lion at Rest' },
  { id: 43, img: '/images/956A2746.webp', caption: 'Two Lions Resting' },
  { id: 44, img: '/images/956A2816.webp', caption: 'Leopard Asleep in the Branches' },
  { id: 45, img: '/images/IMG_0196.webp', caption: 'Sacred Ibis' },
  { id: 46, img: '/images/IMG_0200.webp', caption: 'Warthog on the Move' },
  { id: 47, img: '/images/IMG_0205.webp', caption: 'Ostriches Beneath a Baobab' },
  { id: 48, img: '/images/IMG_0235.webp', caption: 'Elephant Close-Up' },
  { id: 49, img: '/images/IMG_0237.webp', caption: 'Elephant Face to Face' },
  { id: 50, img: '/images/IMG_0239.webp', caption: 'A Pair of Impala' },
  { id: 51, img: '/images/IMG_0376.webp', caption: 'Impala Pair' },
  { id: 53, img: '/images/IMG_1081.webp', caption: 'Meet Your Guide' },
  { id: 54, img: '/images/IMG_1226.webp', caption: 'Looking Over Ngorongoro Crater', featured: true },
  { id: 55, img: '/images/IMG_2503.webp', caption: 'Egrets in the Wildflowers' },
  { id: 56, img: '/images/IMG_2521.webp', caption: 'Mineral Hot Spring' },
  { id: 57, img: '/images/IMG_2562.jpg', caption: 'Mineral-Rich Shoreline' },
  { id: 58, img: '/images/kutoka.jpeg', caption: 'Our Lodge' },
  { id: 59, img: "/images/kutokalodge_1707376322154(1).jpeg", caption: 'Lodge Grounds' },
];

export type Photo = (typeof photos)[number];
