export const destinations = [
  {
    id: 1,
    slug: 'serengeti',
    name: 'Serengeti National Park',
    region: 'Northern Tanzania',
    tag: 'Most Visited',
    heroImg: '/images/px-serengeti-lions.jpg',
    desc: "The world's greatest wildlife spectacle. Witness the Great Migration as over 1.5 million wildebeest thunder across the endless golden plains in search of rain-fed pasture.",
    highlights: ['Great Migration', 'Big Five', 'Hot Air Balloon', 'Endless Plains'],
    bestTime: 'June – October',
    size: '14,763 km²',
    animals: 'Lion · Cheetah · Leopard · Elephant · Buffalo',
    category: 'Safari',
  },
  {
    id: 2,
    slug: 'ngorongoro',
    name: 'Ngorongoro Conservation Area',
    region: 'Northern Tanzania',
    tag: 'UNESCO World Heritage',
    heroImg: '/images/px-ngorongoro-road.jpg',
    desc: "Descend into the world's largest intact volcanic caldera, a self-contained Eden teeming with wildlife at extraordinary density. The crater floor is a guaranteed Big Five encounter.",
    highlights: ['Volcanic Crater', 'Big Five', 'Black Rhino', 'Maasai Culture'],
    bestTime: 'Year-round',
    size: '8,292 km²',
    animals: 'Black Rhino · Lion · Elephant · Hippo · Flamingo',
    category: 'Safari',
  },
  {
    id: 5,
    slug: 'tarangire',
    name: 'Tarangire National Park',
    region: 'Northern Tanzania',
    tag: 'Elephant Paradise',
    heroImg: '/images/px-tarangire-balloon.jpg',
    desc: 'Ancient baobab trees and the largest elephant herds in Tanzania. The Tarangire River is a lifeline attracting thousands of animals during the dry season.',
    highlights: ['Ancient Baobabs', 'Elephant Herds', 'Tree-Climbing Lions', 'Night Drives'],
    bestTime: 'June – October',
    size: '2,850 km²',
    animals: 'Elephant · Greater Kudu · Oryx · Wildebeest · Zebra',
    category: 'Safari',
  },
  {
    id: 6,
    slug: 'manyara',
    name: 'Lake Manyara National Park',
    region: 'Northern Tanzania',
    tag: 'Tree-Climbing Lions',
    heroImg: '/images/px-manyara-flamingos.jpg',
    desc: 'Famous for its tree-climbing lions and flamingo-fringed soda lake. A compact yet spectacular park that rewards visitors with extraordinary wildlife encounters.',
    highlights: ['Tree-Climbing Lions', 'Pink Flamingo', 'Treetop Walkway', 'Hot Springs'],
    bestTime: 'June – October',
    size: '648 km²',
    animals: 'Tree-Climbing Lion · Flamingo · Hippo · Elephant · Blue Monkey',
    category: 'Safari',
  },
  {
    id: 7,
    slug: 'ruaha',
    name: 'Ruaha National Park',
    region: 'Southern Tanzania',
    tag: 'Off the Beaten Path',
    heroImg: '/images/px-ruaha-wild-dogs.jpg',
    desc: "Tanzania's largest national park and best-kept secret. Rugged landscapes, the Great Ruaha River, and an astonishing density of wildlife with virtually no other visitors.",
    highlights: ['Wild Dogs', 'Huge Lion Prides', 'Remote Walks', 'No Crowds'],
    bestTime: 'June – November',
    size: '22,000 km²',
    animals: 'African Wild Dog · Lion · Elephant · Hippo · Sable Antelope',
    category: 'Safari',
  },
  {
    id: 8,
    slug: 'selous',
    name: 'Nyerere National Park (Selous)',
    region: 'Southern Tanzania',
    tag: "Africa's Largest Reserve",
    heroImg: '/images/px-nyerere-hippos.jpg',
    desc: 'A UNESCO World Heritage Site the size of Switzerland. Boat safaris along the Rufiji River reveal hippos, crocodiles, and prolific birdlife alongside extraordinary big game.',
    highlights: ['Boat Safaris', 'Walking Safaris', 'Wild Dogs', 'Rufiji River'],
    bestTime: 'June – October',
    size: '54,600 km²',
    animals: 'African Wild Dog · Hippo · Crocodile · Elephant · Lion',
    category: 'Safari',
  },
  {
    id: 9,
    slug: 'arusha',
    name: 'Arusha National Park',
    region: 'Northern Tanzania',
    tag: 'Day Trip from Arusha',
    heroImg: '/images/px-arusha-meru.jpg',
    desc: "Just 37km from Arusha town, this compact park combines game drives with walking safaris around Ngurdoto Crater, the seven Momella Lakes, and the slopes of Mount Meru — with Kilimanjaro visible on clear days.",
    highlights: ['Ngurdoto Crater', 'Momella Lakes', 'Mount Meru Climb', 'Walking Safaris'],
    bestTime: 'October – April (birding)',
    size: '137 km²',
    animals: 'Colobus Monkey · Giraffe · Buffalo · Hippo · Flamingo',
    category: 'Safari',
  },
];

export type Destination = (typeof destinations)[number];
