export const destinationData = [
  {
    slug: 'serengeti',
    name: 'Serengeti National Park',
    region: 'Northern Tanzania',
    heroImg: 'https://images.unsplash.com/photo-1557456170-0cf4f4d0d362?w=1920&h=1080&fit=crop&auto=format',
    tagline: 'The endless plains where life plays out in full.',
    history: [
      'The name "Serengeti" comes from the Maasai word Siringet  meaning "the place where the land runs on forever." For thousands of years, Maasai pastoralists grazed their cattle across these plains alongside lion, elephant, and wildebeest, developing a coexistence with wildlife that shaped the entire ecosystem.',
      'In 1929, the British colonial government declared the area a partial game reserve, and in 1951 the Serengeti became Tanzania\'s first national park. The work of naturalists Bernhard and Michael Grzimek  whose 1959 film "Serengeti Shall Not Die" won an Academy Award  brought the park to global attention and helped establish its final boundaries.',
      'Today the Serengeti is recognised as one of the Seven Natural Wonders of Africa and a UNESCO World Heritage Site. Its 14,763 km² of savanna, woodland, and riverine forest sustain the largest terrestrial mammal migration on earth  over 1.5 million wildebeest, 500,000 gazelle, and 200,000 zebra moving in a continuous clockwise circuit in search of rain and grass.',
    ],
    facts: { size: '14,763 km²', bestTime: 'June – October', animals: 'Lion · Cheetah · Leopard · Elephant · Buffalo · Wildebeest' },
    highlights: ['Great Migration', 'Big Five', 'Hot Air Balloon Safaris', 'Kopjes & Rock Formations', 'Predator Concentrations'],
    relatedTours: [
      { id: 2, name: '3 Days Classic Serengeti Safari', duration: '3 Days / 2 Nights', img: '/images/956A2358.jpg' },
      { id: 4, name: '6 Days Best of Tanzania Safari', duration: '6 Days / 5 Nights', img: '/images/956A3309.jpg' },
      { id: 5, name: '8 Days Best of Northern Tanzania Safari', duration: '8 Days / 7 Nights', img: '/images/956A2613.jpg' },
      { id: 6, name: '8 Days Wildebeest Migration River Crossing', duration: '8 Days / 7 Nights', img: '/images/956A4274.jpg' },
    ],
  },
  {
    slug: 'ngorongoro',
    name: 'Ngorongoro Conservation Area',
    region: 'Northern Tanzania',
    heroImg: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=1920&h=1080&fit=crop&auto=format',
    tagline: 'A world within a crater  ancient, intact, and unforgettable.',
    history: [
      'Ngorongoro Crater was formed around three million years ago when a giant volcano exploded and collapsed inward, creating one of the largest intact calderas on earth. The crater floor  roughly 260 km²  became a self-contained world, sheltering an extraordinary density of wildlife within its 600-metre-high walls.',
      'The Maasai people have lived alongside wildlife in the Ngorongoro highlands for centuries, grazing their cattle on the crater rim and the surrounding plains. When Tanzania\'s national park system was established in the 1950s, the Maasai retained rights within Ngorongoro  making it one of the only protected areas in the world where indigenous communities and wildlife share the same land.',
      'Declared a UNESCO World Heritage Site in 1979, Ngorongoro is also home to Olduvai Gorge  the "Cradle of Mankind"  where paleoanthropologist Louis Leakey discovered some of the oldest hominin fossils ever found, placing human origins in this very landscape.',
    ],
    facts: { size: '8,292 km²', bestTime: 'Year-round', animals: 'Black Rhino · Lion · Elephant · Hippo · Flamingo · Hyena' },
    highlights: ['Volcanic Caldera', 'Black Rhino Sightings', 'Big Five in One Day', 'Olduvai Gorge', 'Maasai Culture'],
    relatedTours: [
      { id: 1, name: '1 Day Ngorongoro Crater Safari', duration: '1 Day', img: '/images/956A3279.jpg' },
      { id: 4, name: '6 Days Best of Tanzania Safari', duration: '6 Days / 5 Nights', img: '/images/956A3309.jpg' },
      { id: 5, name: '8 Days Best of Northern Tanzania Safari', duration: '8 Days / 7 Nights', img: '/images/956A2613.jpg' },
    ],
  },
  {
    slug: 'zanzibar',
    name: 'Zanzibar Archipelago',
    region: 'Indian Ocean Islands',
    heroImg: 'https://images.unsplash.com/photo-1573160813959-7ea66e14e673?w=1920&h=1080&fit=crop&auto=format',
    tagline: 'A thousand years of trade, spice, and ocean breeze.',
    history: [
      'Zanzibar\'s story is one of the most layered in the world. For over a thousand years the island sat at the crossroads of Indian Ocean trade routes, drawing Arab merchants, Persian sailors, Indian traders, and Portuguese explorers  each leaving a mark on its language, architecture, food, and culture.',
      'In the 19th century, Zanzibar became the capital of the Omani Sultanate and one of the most important ports in East Africa  a centre for the clove trade and, tragically, the Arab slave trade. The old slave market in Stone Town  now a cathedral and memorial  bears silent witness to that history.',
      'British rule brought abolition in 1873, and in 1963 Zanzibar became independent before merging with Tanganyika to form Tanzania in 1964. Stone Town was designated a UNESCO World Heritage Site in 2000. Beyond the history, Zanzibar\'s beaches  Nungwi, Kendwa, Paje  rank among the finest in the world.',
    ],
    facts: { size: '2,643 km²', bestTime: 'June – October & Jan – February', animals: 'Humpback Whale · Dolphin · Sea Turtle · Red Colobus Monkey' },
    highlights: ['Stone Town UNESCO Heritage', 'Kendwa & Nungwi Beaches', 'Spice Farm Tours', 'Dolphin Watching', 'Swahili Cuisine'],
    relatedTours: [
      { id: 9, name: '4 Days Zanzibar Kendwa Beach & Stone Town Tour', duration: '4 Days / 3 Nights', img: '/images/stone-town.jpg' },
      { id: 10, name: '8 Days Tanzania Cultural Tour', duration: '8 Days / 7 Nights', img: '/images/956A1769.jpg' },
    ],
  },
  {
    slug: 'kilimanjaro',
    name: 'Mount Kilimanjaro',
    region: 'Northern Tanzania',
    heroImg: 'https://images.unsplash.com/photo-1621414050946-1a8d2a9d7c5b?w=1920&h=1080&fit=crop&auto=format',
    tagline: "Africa's roof  a summit that changes everyone who climbs it.",
    history: [
      'Kilimanjaro is the highest free-standing mountain in the world, rising 5,895 metres above sea level from the surrounding plains of northern Tanzania. Its three volcanic cones  Kibo, Mawenzi, and Shira  were formed over a million years ago, and Kibo\'s crater still shows signs of geothermal activity.',
      'The Chagga people have lived on Kilimanjaro\'s fertile slopes for centuries, farming coffee, bananas, and maize in the rich volcanic soil. The mountain holds deep spiritual significance in their culture  it is home to their ancestors and the source of rivers that sustain entire communities.',
      'The first recorded summit was reached in 1889 by Hans Meyer and Ludwig Purtscheller. Today over 50,000 people attempt the climb each year via routes including the Lemosho, Machame, Marangu, and Rongai trails  each passing through five distinct climatic zones from tropical rainforest to arctic summit.',
    ],
    facts: { size: '756 km² (park)', bestTime: 'January – March & June – October', animals: 'Elephant · Buffalo · Leopard · Colobus Monkey · Sunbird' },
    highlights: ['Uhuru Peak at 5,895m', 'Five Climatic Zones', 'Glacier Views', 'Chagga Culture', 'Lemosho & Machame Routes'],
    relatedTours: [
      { id: 5, name: '8 Days Best of Northern Tanzania Safari', duration: '8 Days / 7 Nights', img: '/images/956A2613.jpg' },
      { id: 10, name: '8 Days Tanzania Cultural Tour', duration: '8 Days / 7 Nights', img: '/images/956A1769.jpg' },
    ],
  },
  {
    slug: 'tarangire',
    name: 'Tarangire National Park',
    region: 'Northern Tanzania',
    heroImg: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1920&h=1080&fit=crop&auto=format',
    tagline: 'Ancient baobabs, elephant herds, and a river that never runs dry.',
    history: [
      'Tarangire takes its name from the Tarangire River  the only permanent water source in the region during Tanzania\'s long dry season. This single fact shapes the entire ecosystem: every dry season, thousands of animals converge on the riverbanks in one of the most dramatic wildlife concentrations in Africa.',
      'The park was established in 1970, covering 2,850 km² of savanna, woodland, and seasonal swamp. Its character is defined by two things  elephants and baobabs. Tarangire has one of the highest elephant densities in Tanzania, with herds of 300 or more a common sight during the dry season. The ancient baobab trees, some over 1,000 years old, give the landscape a primordial quality unlike any other park in East Africa.',
      'The park hosts exceptional birdlife  over 550 recorded species  making it a favourite among birding enthusiasts. The local Barbaig and Maasai communities have used the surrounding land for centuries, and their relationship with the wildlife corridors connecting Tarangire to the greater ecosystem remains critical to conservation.',
    ],
    facts: { size: '2,850 km²', bestTime: 'June – October', animals: 'Elephant · Lion · Leopard · Gerenuk · Oryx · Python' },
    highlights: ['Giant Elephant Herds', 'Ancient Baobab Trees', '550+ Bird Species', 'Swamp Wildlife', 'Dry Season Spectacle'],
    relatedTours: [
      { id: 3, name: '4 Nights / 5 Days Northern Safari', duration: '5 Days / 4 Nights', img: '/images/elephantsafari.png' },
      { id: 4, name: '6 Days Best of Tanzania Safari', duration: '6 Days / 5 Nights', img: '/images/956A3309.jpg' },
      { id: 5, name: '8 Days Best of Northern Tanzania Safari', duration: '8 Days / 7 Nights', img: '/images/956A2613.jpg' },
    ],
  },
  {
    slug: 'arusha',
    name: 'Arusha National Park',
    region: 'Northern Tanzania',
    heroImg: 'https://images.unsplash.com/photo-1623743423143-23df3234ae5c?w=1920&h=1080&fit=crop&auto=format',
    tagline: 'A wild gem hiding in plain sight  37km from the city.',
    history: [
      'Arusha National Park is the smallest but perhaps the most ecologically diverse park in Tanzania. Established in 1960 and covering just 137 km², it packs an extraordinary range of habitats into a compact space  from the forests of Ngurdoto Crater to the glittering Momella Lakes and the dramatic slopes of Mount Meru, Tanzania\'s second-highest peak at 4,566 metres.',
      'The park sits just 37km east of Arusha town  the safari capital of East Africa  making it the most accessible wilderness in the country. Despite its proximity to the city, Arusha receives a fraction of the visitors that flock to the Serengeti or Ngorongoro, preserving a quiet, intimate atmosphere that is increasingly rare in Tanzanian parks.',
      'The Momella Lakes, fed by underground streams from Mount Meru, attract large flocks of flamingo and other waterbirds. The forests shelter the striking black-and-white colobus monkey, while the open grasslands host giraffe, buffalo, zebra, and waterbuck. On clear days, Kilimanjaro is visible on the horizon  a reminder of the extraordinary landscapes that surround this small but remarkable park.',
    ],
    facts: { size: '137 km²', bestTime: 'October – April (birding)', animals: 'Colobus Monkey · Giraffe · Buffalo · Hippo · Flamingo · Leopard' },
    highlights: ['Ngurdoto Crater', 'Momella Lakes', 'Mount Meru Climb', 'Walking Safaris', 'Kilimanjaro Views'],
    relatedTours: [
      { id: 2, name: '3 Days Classic Serengeti Safari', duration: '3 Days / 2 Nights', img: '/images/956A2358.jpg' },
      { id: 3, name: '4 Nights / 5 Days Northern Safari', duration: '5 Days / 4 Nights', img: '/images/elephantsafari.png' },
      { id: 5, name: '8 Days Best of Northern Tanzania Safari', duration: '8 Days / 7 Nights', img: '/images/956A2613.jpg' },
    ],
  },
];
