import type { Lodge } from './types';

export const lodges: Lodge[] = [
  {
    id: 8,
    name: 'Kutoka Lodge',
    type: 'Boutique Lodge',
    location: 'Kisongo, Arusha',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.0,
    img: '/images/kutoka.jpeg',
    img2: '/images/kutokalodge_1707376322154(1).jpeg',
    desc: 'A garden lodge in Kisongo, just outside Arusha on the road to every northern park, so it\'s an easy first or last night of a safari. Rooms open onto lawns and garden views, each with a private shower room, toiletries, hairdryer and slippers. Simba, the on-site restaurant, serves international, grill and BBQ dishes with vegetarian, vegan and gluten-free options, and breakfast is buffet, à la carte or continental.',
    amenities: ['Simba Restaurant (international & grill)', 'Bar', 'Garden & terrace', 'Children\'s playground', 'Room service', 'Free Wi-Fi', 'Free private parking', 'Bicycle & car rental', 'Airport shuttle (on request)'],
    highlight: 'Minutes from Arusha, on the road to every northern circuit park',
    bestFor: ['Families', 'First & Last Night Stays', 'Northern Circuit Stopovers'],
    season: 'Year-round',
  },
  {
    id: 7,
    name: 'Kuona Serengeti Lodge',
    type: 'Luxury Tented Lodge',
    location: 'Serengeti National Park',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 5.0,
    img: '/images/956A2725.webp',
    img2: '/images/956A2633.webp',
    desc: 'Built into the Serengeti\'s kopjes, Kuona ("to see" in Swahili) is a luxury lodge designed to disappear into the landscape. Spacious suites look out over the valley, and the lodge pairs game drives with a full wellness side: The Sanctuary spa with massage rooms, an outdoor pool and a fine-dining restaurant cooking to order from breakfast onward.',
    amenities: ['The Sanctuary spa & massage rooms', 'Outdoor pool', 'Fine-dining restaurant', 'Bar & coffee shop', 'Valley-view suites', 'Cooked-to-order breakfast', 'Free in-room Wi-Fi', 'Laundry service', 'Game drives'],
    highlight: 'Built into ancient kopjes — the Serengeti as it was meant to be seen',
    bestFor: ['Couples', 'Artists & Storytellers', 'Conservation Travellers'],
    season: 'Year-round · Best Jun–Oct',
  },
  {
    id: 1,
    name: 'Elewana Serengeti Pioneer Camp',
    type: 'Classic Tented Camp',
    location: 'Moru Kopjes, South-Central Serengeti',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 4.8,
    img: '/images/956A3195.webp',
    img2: '/images/956A3373.webp',
    desc: 'Twelve canvas tents on a kopje in the south-central Serengeti, styled after the explorers\' camps of the 1930s, with views over the Moru Kopjes and Lake Magadi. Each tent has a queen bed under a mosquito net, campaign furniture, a writing desk and a shaded veranda, with a flush toilet and solar-heated shower en suite. The lounge sits under a makuti thatch roof, dinner is served in the dining tent, and there\'s a plunge pool and an evening campfire.',
    amenities: ['12 en-suite tents (incl. 1 family tent)', 'Solar-heated showers & flush toilets', 'Plunge pool with sun loungers', 'Thatched lounge with Moru Kopjes views', 'Dining tent & bar', 'Evening campfire', 'Personal tent attendant', 'Solar power 24h & Wi-Fi', 'Room service'],
    highlight: '1930s explorer tents above the Moru Kopjes',
    bestFor: ['Couples', 'Wildlife Lovers', 'First Safaris'],
    season: 'Year-round · Best Dec–Mar & Jun–Oct',
  },
  {
    id: 2,
    name: 'Ngorongoro Serena Safari Lodge',
    type: 'Safari Lodge',
    location: 'Western Crater Rim, Ngorongoro',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.7,
    img: '/images/IMG_0236.webp',
    img2: '/images/956A2659.webp',
    desc: 'Built from river stone and cloaked in vines along the western rim of the Ngorongoro Crater, the lodge is almost invisible from the crater floor 600m below. Rooms have a twin or double bed, en-suite bathroom, safe and a private stone balcony looking straight into the caldera. The restaurant upstairs has two fireplaces and panoramic windows over the crater, with a wood-panelled bar, lounge and curio shop below.',
    amenities: ['Private stone balcony with crater view', 'Restaurant with panoramic windows', 'Bar & lounge with fireplaces', 'Massage & beauty treatments', 'Curio shop', 'Room service (suites)', 'Free Wi-Fi', 'Laundry service', 'Babysitting & children\'s menus'],
    highlight: 'Every room looks straight down into the crater',
    bestFor: ['Honeymoons', 'Special Occasions', 'First Safaris'],
    season: 'Year-round',
  },
  {
    id: 3,
    name: 'Zuri Zanzibar',
    type: 'Beach Resort',
    location: 'Kendwa Beach, Zanzibar',
    category: 'Beach Resorts',
    price: 'Price on request',
    rating: 4.8,
    img: '/images/px-lodge-nungwi-aerial.jpg',
    img2: '/images/px-lodge-dhow-dusk.jpg',
    desc: 'A 32-acre resort on the beach at Kendwa, on Zanzibar\'s northwest coast, with sunset views over Tumbatu Island and a beach you can swim from at any tide. Its 56 bungalows, suites and villas all have air conditioning, outdoor showers and terraces; suites add a living room and outdoor jacuzzi, and villas have private pools. There are three restaurants, four bars, the sea-front Maua spa and a full watersports centre.',
    amenities: ['Private beach & infinity pool', '3 restaurants & 4 bars', 'Maua Wellness Spa & salon', 'Spice garden & cooking classes', 'Gym, outdoor fitness & yoga', 'Snorkelling, kayaks & paddle boards', 'Dhow cruises, fishing & PADI diving', 'Villas with private pools', 'Air conditioning & outdoor showers'],
    highlight: 'Swimmable at every tide, with sunset over the ocean',
    bestFor: ['Couples', 'Post-Safari Extension', 'Families'],
    season: 'Jun–Oct & Dec–Feb',
  },
  {
    id: 4,
    name: 'Elewana Tarangire Treetops',
    type: 'Treehouse Lodge',
    location: 'Private concession bordering Tarangire',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.8,
    img: '/images/IMG_0235.webp',
    img2: '/images/956A1611.webp',
    desc: 'Twenty treehouse rooms raised on stilts among marula and baobab trees, on a private concession bordering Tarangire National Park. At 65m², they\'re among the largest rooms in East Africa, each open-fronted with a wide balcony and a double shower. The main lodge is built around a thousand-year-old baobab and looks over a pool and a waterhole that elephants visit through the day.',
    amenities: ['20 elevated treehouse rooms (65m²)', 'Double shower en suite', 'Pool overlooking a waterhole', 'Restaurant, bar & lounge', 'Boma dinners & poolside dining', 'Walking safaris', 'Night game drives', 'Free supervised childcare', 'Laundry & free in-room Wi-Fi'],
    highlight: 'Sleep up in the trees, around a 1,000-year-old baobab',
    bestFor: ['Families', 'Unique Experiences', 'Wildlife Lovers'],
    season: 'Jun–Feb · Best Jul–Oct',
  },
  {
    id: 5,
    name: 'Ruaha River Lodge',
    type: 'Safari Lodge',
    location: 'Great Ruaha River, Ruaha National Park',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.6,
    img: '/images/956A2816.webp',
    img2: '/images/956A3570.webp',
    desc: 'Run by the Fox family, safari pioneers in southern Tanzania, the lodge is two camps (River and Hilltop) with 24 stone chalets along the Great Ruaha River. Each chalet is built of dressed river stone under a makuti thatch roof, with netted openings on three sides and a front deck facing the river. One dining area sits on a rocky kopje with views across the park; the other is down by the water where animals come to drink.',
    amenities: ['24 river-view stone chalets', 'Private deck over the river', 'Kopje-top dining & bar', 'Riverside dining & bar', 'Morning & afternoon game drives', 'Full-day safaris', 'Guided walking safaris', 'Gym', 'Terrace & gardens'],
    highlight: 'Family-run, right on the Great Ruaha River',
    bestFor: ['Adventurers', 'Repeat Safari-Goers', 'Photographers'],
    season: 'Jun–Nov',
  },
  {
    id: 6,
    name: 'Sand Rivers Selous',
    type: 'Riverside Lodge',
    location: 'Rufiji River, Nyerere National Park (Selous)',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 4.9,
    img: '/images/956A3279.webp',
    img2: '/images/956A1555.webp',
    desc: 'An intimate lodge on a broad bend of the Rufiji River in Nyerere National Park, founded by the renowned guide Richard Bonham and run by Nomad Tanzania. There are just eight cottages, raised on decks and built of timber, stone and thatch: five Riverside rooms and three Hillside Suites with a living area and private plunge pool. Stays are full board, including drinks, Wi-Fi and laundry.',
    amenities: ['8 cottages (Hillside Suites with plunge pools)', 'Swimming pool over the river', 'Lounge, library & bar', 'Private dining', 'Game drives', 'Walking safaris', 'Boat safaris on the Rufiji', 'Fly-camping', 'Full board incl. drinks & laundry'],
    highlight: 'Walking and boating safaris on the Rufiji River',
    bestFor: ['Wildlife Enthusiasts', 'Remote Seekers', 'Walkers'],
    season: 'Jun–Mar',
  },
];
