import type { Lodge } from './types';

export const lodges: Lodge[] = [
  {
    id: 8,
    name: 'Kutoka Lodge',
    type: 'Boutique Lodge',
    location: 'Kisongo, Arusha',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.0,
    img: '/images/kutoka.jpeg',
    img2: '/images/kutokalodge_1707376322154(1).jpeg',
    desc: 'A garden lodge just outside Arusha in Kisongo, right on the route to the northern circuit parks. Thatched-roof stone rooms open onto a brick-paved courtyard and lawns, with family rooms, garden views, and a relaxed restaurant and bar — a comfortable stop before or after the parks rather than a destination in itself.',
    amenities: ['Garden & Terrace', 'Restaurant & Bar', 'Free Wi-Fi', 'Family Rooms', 'Airport Transfers', 'Continental Breakfast'],
    highlight: 'Minutes from Arusha, on the road to every northern circuit park',
    bestFor: ['Families', 'First & Last Night Stays', 'Northern Circuit Stopovers'],
    season: 'Year-round',
  },
  {
    id: 7,
    name: 'Kuona Serengeti Lodge',
    type: 'Luxury Tented Lodge',
    location: 'Serengeti National Park',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 5.0,
    img: '/images/956A3123.webp',
    img2: '/images/956A4274.webp',
    desc: 'Built within ancient kopjes using materials that echo the Serengeti\'s own landscape, Kuona — meaning "to see" in Swahili — offers a new way to witness Africa\'s wilderness. Luxury tented suites blend seamlessly into the terrain, with the Great Migration, lion territory, and timeless savanna as your horizon.',
    amenities: ['World-Class Spa', 'Sauna', 'À La Carte Dining', 'Game Drives', 'Creative Studio', 'Conservation Experiences'],
    highlight: 'Built into ancient kopjes — the Serengeti as it was meant to be seen',
    bestFor: ['Couples', 'Artists & Storytellers', 'Conservation Travellers'],
    season: 'Year-round · Best Jun–Oct',
  },
  {
    id: 1,
    name: 'Elewana Serengeti Pioneer Camp',
    type: 'Classic Tented Camp',
    location: 'Moru Kopjes, South-Central Serengeti',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 4.8,
    img: '/images/956A3225.webp',
    img2: '/images/956A2358.webp',
    desc: 'Twelve canvas tents on a rocky kopje in the south-central Serengeti, styled after the explorers\' camps of the 1930s — period lamps, weathered dressers and copper basins, with solar-heated showers en suite. The lounge looks straight out over the Moru Kopjes and the open plains.',
    amenities: ['En-Suite Tents', 'Kopje-Top Lounge', 'Bush Dining', 'Game Drives', 'Solar Hot Showers', 'Moru Kopjes Views'],
    highlight: '1930s explorer tents above the Moru Kopjes',
    bestFor: ['Couples', 'Wildlife Lovers', 'First Safaris'],
    season: 'Year-round · Best Dec–Mar & Jun–Oct',
  },
  {
    id: 2,
    name: 'Ngorongoro Serena Safari Lodge',
    type: 'Safari Lodge',
    location: 'Western Crater Rim, Ngorongoro',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.7,
    img: '/images/956A4243.webp',
    img2: '/images/IMG_1256.webp',
    desc: 'Built from river stone and cloaked in wild vines along the crater rim, so it is almost invisible from the floor 600m below. All 75 rooms have a private stone balcony looking straight down into the caldera, and the design takes its cue from nearby Olduvai Gorge, the Cradle of Mankind.',
    amenities: ['Crater Views', 'Private Stone Balcony', 'Heated Rooms', 'Restaurant & Bar', 'Guided Crater Walks', 'Early Crater Access'],
    highlight: 'Every room looks straight down into the crater',
    bestFor: ['Honeymoons', 'Special Occasions', 'First Safaris'],
    season: 'Year-round',
  },
  {
    id: 3,
    name: 'Zuri Zanzibar',
    type: 'Beach Resort',
    location: 'Kendwa Beach, Zanzibar',
    category: 'Beach Resorts',
    price: 'Price on request',
    rating: 4.8,
    img: '/images/nakupenda-beach.webp',
    img2: '/images/prison.webp',
    desc: 'Bungalows, suites and villas on Kendwa Beach, one of the few Zanzibar beaches you can swim from at any tide. Villas have private infinity pools, and the resort has its own spice garden where you can join a Swahili cooking class, plus a spa and three restaurants.',
    amenities: ['Private Beach', 'Infinity Pool', 'Spice Garden', 'Swahili Cooking Class', 'Spa', 'Water Sports'],
    highlight: 'Swimmable at every tide, with sunset over the ocean',
    bestFor: ['Couples', 'Post-Safari Extension', 'Families'],
    season: 'Jun–Oct & Dec–Feb',
  },
  {
    id: 4,
    name: 'Elewana Tarangire Treetops',
    type: 'Treehouse Lodge',
    location: 'Private concession bordering Tarangire',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.8,
    img: '/images/IMG_0227.webp',
    img2: '/images/956A3309.webp',
    desc: 'Twenty treehouse rooms raised on stilts among marula and baobab trees, each with a private open-fronted balcony. The main lodge is built around a thousand-year-old baobab and looks over a pool and a waterhole that elephants visit through the day.',
    amenities: ['Elevated Treehouse Rooms', 'Waterhole Views', 'Walking Safaris', 'Pool', 'Night Game Drives', 'Sundowner Deck'],
    highlight: 'Sleep up in the trees, around a 1,000-year-old baobab',
    bestFor: ['Families', 'Unique Experiences', 'Wildlife Lovers'],
    season: 'Jun–Feb · Best Jul–Oct',
  },
  {
    id: 5,
    name: 'Ruaha River Lodge',
    type: 'Safari Lodge',
    location: 'Great Ruaha River, Ruaha National Park',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.6,
    img: '/images/956A3701.webp',
    img2: '/images/956A2613.webp',
    desc: 'Stone chalets strung along the bank of the Great Ruaha River, run by the Fox family, who have been operating camps in southern Tanzania for decades. Each chalet has a private deck over the river, and there are two dining areas: one on a rocky kopje and one down by the water.',
    amenities: ['River Views', 'Private Deck', 'Game Drives', 'Kopje-Top Dining', 'Riverside Bar', 'Family-Run'],
    highlight: 'Family-run, right on the Great Ruaha River',
    bestFor: ['Adventurers', 'Repeat Safari-Goers', 'Photographers'],
    season: 'Jun–Nov',
  },
  {
    id: 6,
    name: 'Sand Rivers Selous',
    type: 'Riverside Lodge',
    location: 'Rufiji River, Nyerere National Park (Selous)',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 4.9,
    img: '/images/956A2192.webp',
    img2: '/images/956A2874.webp',
    desc: 'An intimate lodge on a rocky bend of the Rufiji River in Nyerere National Park, the former Selous Game Reserve. It was founded by the guide Richard Bonham. Days mix game drives, boat trips upriver towards Stiegler\'s Gorge, and some of the best walking safaris in Africa.',
    amenities: ['Boat Safaris', 'Walking Safaris', 'Fly-Camping', 'Game Drives', 'Fishing (Seasonal)', 'Fly-In Access'],
    highlight: 'Walking and boating safaris on the Rufiji River',
    bestFor: ['Wildlife Enthusiasts', 'Remote Seekers', 'Walkers'],
    season: 'Jun–Mar',
  },
];
