import type { Lodge } from './types';

export const lodges: Lodge[] = [
  {
    id: 8,
    name: 'Kutoka Lodge',
    type: 'Boutique Lodge',
    location: 'Kisongo, Arusha',
    category: 'Luxury Lodges',
    price: 'Price on request',
    rating: 4.0,
    img: '/images/kutoka.jpeg',
    img2: '/images/kutokalodge_1707376322154(1).jpeg',
    desc: 'A garden lodge just outside Arusha in Kisongo, right on the route to the northern circuit parks. Thatched-roof stone rooms open onto a brick-paved courtyard and lawns, with family rooms, garden views, and a relaxed restaurant and bar — a comfortable stop before or after the parks rather than a destination in itself.',
    amenities: ['Garden & Terrace', 'Restaurant & Bar', 'Free Wi-Fi', 'Family Rooms', 'Airport Transfers', 'Continental Breakfast'],
    highlight: 'Minutes from Arusha, on the road to every northern circuit park',
    bestFor: ['Families', 'First & Last Night Stays', 'Northern Circuit Stopovers'],
    season: 'Year-round',
  },
  {
    id: 7,
    name: 'Kuona Serengeti Lodge',
    type: 'Luxury Tented Lodge',
    location: 'Serengeti National Park',
    category: 'Tented Camps',
    price: 'Price on request',
    rating: 5.0,
    img: '/images/956A3123.webp',
    img2: '/images/956A4274.webp',
    desc: 'Built within ancient kopjes using materials that echo the Serengeti\'s own landscape, Kuona — meaning "to see" in Swahili — offers a new way to witness Africa\'s wilderness. Luxury tented suites blend seamlessly into the terrain, with the Great Migration, lion territory, and timeless savanna as your horizon.',
    amenities: ['World-Class Spa', 'Sauna', 'À La Carte Dining', 'Game Drives', 'Creative Studio', 'Conservation Experiences'],
    highlight: 'Built into ancient kopjes — the Serengeti as it was meant to be seen',
    bestFor: ['Couples', 'Artists & Storytellers', 'Conservation Travellers'],
    season: 'Year-round · Best Jun–Oct',
  },
  {
    id: 1,
    name: 'Serengeti Horizon Camp',
    type: 'Luxury Tented Camp',
    location: 'Central Serengeti',
    category: 'Tented Camps',
    price: 'From $680/night',
    rating: 5.0,
    img: '/images/956A3225.webp',
    img2: '/images/956A2358.webp',
    desc: 'Sixteen spacious canvas tents with uninterrupted Serengeti views. Plunge pools, en-suite bathrooms, and gourmet bush dining under a canopy of stars. Each tent faces the open plains, giving you front-row seats to the drama of one of the world\'s greatest wildlife theatres.',
    amenities: ['Plunge Pool', 'En-Suite Bathroom', 'Bush Dining', 'Game Drives', 'Wi-Fi', 'Spa'],
    highlight: 'Closest camp to the Great Migration crossings',
    bestFor: ['Couples', 'Wildlife Lovers', 'First Safaris'],
    season: 'Year-round · Best Jun–Oct',
  },
  {
    id: 2,
    name: 'Crater Highlands Lodge',
    type: 'Luxury Lodge',
    location: 'Crater Rim, Ngorongoro',
    category: 'Luxury Lodges',
    price: 'From $1,200/night',
    rating: 5.0,
    img: '/images/956A4243.webp',
    img2: '/images/IMG_1256.webp',
    desc: 'Perched on the Crater rim with sweeping views into the caldera. Colonial-meets-Maasai architecture, attentive service, and guided descents into the crater floor. Your suite overlooks the world\'s largest intact volcanic caldera — home to over 25,000 animals.',
    amenities: ['Crater Views', 'Attentive Service', 'Guided Descents', 'Fireplace', 'Lounge', 'Wine Cellar'],
    highlight: 'Crater-rim views over one of Africa\'s greatest wildlife sanctuaries',
    bestFor: ['Honeymoons', 'Special Occasions', 'Luxury Seekers'],
    season: 'Year-round · Best Jan–Mar',
  },
  {
    id: 3,
    name: 'Zanzibar Coral Beach Villas',
    type: 'Beach Resort',
    location: 'North Zanzibar',
    category: 'Beach Resorts',
    price: 'From $520/night',
    rating: 4.9,
    img: '/images/nakupenda-beach.webp',
    img2: '/images/prison.webp',
    desc: "Private oceanfront villas on Zanzibar's north coast. Infinity pools, water sports, spice tours, and Swahili-inspired fine dining. The perfect post-safari escape where the Indian Ocean meets centuries of island culture.",
    amenities: ['Private Beach', 'Infinity Pool', 'Water Sports', 'Spice Tours', 'Wi-Fi', 'Spa'],
    highlight: 'A quiet stretch of Zanzibar\'s north coast',
    bestFor: ['Couples', 'Post-Safari Extension', 'Families'],
    season: 'Jun–Oct & Dec–Feb',
  },
  {
    id: 4,
    name: 'Tarangire Baobab Retreat',
    type: 'Luxury Lodge',
    location: 'Tarangire National Park',
    category: 'Luxury Lodges',
    price: 'From $750/night',
    rating: 4.8,
    img: '/images/IMG_0227.webp',
    img2: '/images/956A3309.webp',
    desc: 'Elevated rooms set among the baobabs of the Tarangire ecosystem. Wake to elephant herds at the waterhole below your private deck. A bush experience built around the park\'s ancient baobab trees and its famously dense elephant population.',
    amenities: ['Elevated Rooms', 'Elephant Viewing', 'Guided Walks', 'Pool', 'Sundowner Deck', 'Naturalist Guide'],
    highlight: 'Set among Tarangire\'s ancient baobabs and elephant herds',
    bestFor: ['Families', 'Unique Experiences', 'Wildlife Lovers'],
    season: 'Jun–Feb · Best Jul–Oct',
  },
  {
    id: 5,
    name: 'Ruaha Wilderness Camp',
    type: 'Luxury Lodge',
    location: 'Ruaha National Park',
    category: 'Luxury Lodges',
    price: 'From $580/night',
    rating: 4.9,
    img: '/images/956A3701.webp',
    img2: '/images/956A2613.webp',
    desc: "Rock chalets above the Great Ruaha River — Tanzania's last true wilderness frontier. Walking safaris, boat activities, and extraordinary remoteness. One of the continent's most off-the-beaten-track luxury experiences.",
    amenities: ['River Views', 'Walking Safaris', 'Boat Trips', 'Pool', 'No Wi-Fi (Off-grid)', 'Star Beds'],
    highlight: 'Off-the-beaten-track wilderness on the Great Ruaha River',
    bestFor: ['Adventurers', 'Off-Grid Travellers', 'Repeat Safari-Goers'],
    season: 'Jun–Nov',
  },
  {
    id: 6,
    name: 'Selous Migration Camp',
    type: 'Tented Camp',
    location: 'Selous Game Reserve',
    category: 'Tented Camps',
    price: 'From $490/night',
    rating: 4.8,
    img: '/images/956A2192.webp',
    img2: '/images/956A2874.webp',
    desc: "A fly-in camp on the banks of the Rufiji River, deep in Africa's largest game reserve. Boat safaris, walking, and some of the continent's best wild dog sightings. Accessible only by light aircraft — the ultimate remote safari.",
    amenities: ['Boat Safaris', 'Walking Safaris', 'Wild Dog Tracking', 'Bush Meals', 'Fly-In Access', 'Stargazing'],
    highlight: 'Highest wild dog density in Africa',
    bestFor: ['Wildlife Enthusiasts', 'Remote Seekers', 'Photographers'],
    season: 'Jul–Nov',
  },
];
