'use client';

import { useState } from 'react';

// Widths generated by scripts/optimize-images.mjs (runs before every build).
const WIDTHS = [640, 1280, 1920];

// Photos in /images/ have small/medium/large WebP copies in /img/; the browser
// picks the smallest one that fills the slot, so a phone gets ~50 KB instead
// of the 500 KB+ original. Anything outside /images/ is used as-is.
function responsive(src: string) {
  const m = src.match(/^\/images\/(.+)\.(jpe?g|png|webp)$/i);
  if (!m) return { src };
  const base = `/img/${encodeURIComponent(m[1])}`;
  return {
    src: `${base}-1280.webp`,
    srcSet: WIDTHS.map((w) => `${base}-${w}.webp ${w}w`).join(', '),
  };
}

// Fills its (relatively positioned) parent like a CSS cover background, but as
// a real <img>, so it lazy-loads below the fold and gets a blur-to-sharp reveal.
// `sizes` tells the browser how wide the slot is — pass e.g. "33vw" for a
// three-column card so it doesn't fetch a full-width image.
export default function CoverImage({
  src,
  alt = '',
  className = '',
  priority = false,
  sizes = '(min-width: 1024px) 60vw, 100vw',
}: {
  src: string;
  alt?: string;
  className?: string;
  priority?: boolean;
  sizes?: string;
}) {
  const [loaded, setLoaded] = useState(false);
  const img = responsive(src);
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      {...img}
      sizes={img.srcSet ? sizes : undefined}
      alt={alt}
      loading={priority ? 'eager' : 'lazy'}
      fetchPriority={priority ? 'high' : 'auto'}
      decoding="async"
      onLoad={() => setLoaded(true)}
      ref={(el) => { if (el?.complete) setLoaded(true); }}
      className={`absolute inset-0 w-full h-full object-cover ${className}`}
      style={{
        backgroundColor: 'rgba(109,103,83,0.06)',
        filter: loaded ? 'blur(0px)' : 'blur(16px)',
        transition: 'filter 0.6s ease',
      }}
    />
  );
}
