export const toursMore = [
  {
    id: 6,
    name: '8 Days Wildebeest Migration River Crossing',
    duration: '8 Days / 7 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Migration',
    groupLabel: 'Private safari',
    img: '/images/956A4274.jpg',
    highlight: 'Migration Special',
    desc: 'Follow the Great Migration from Tarangire to the Mara River crossings in the northern Serengeti, with an optional hot air balloon flight (from $546pp), before finishing with the Ngorongoro Crater, Olduvai Gorge and Lake Manyara.',
    parks: ['Tarangire', 'Serengeti (Seronera, Kogatende, North Mara)', 'Ngorongoro', 'Olduvai Gorge & Laetoli', 'Lake Manyara'],
    itinerary: [
      { day: 'Day 1', title: 'Arusha – Tarangire National Park', text: 'Game drive in Tarangire - large elephant herds, tree-climbing lions and the iconic baobab "Tree of Life".' },
      { day: 'Day 2', title: 'Serengeti National Park (Seronera)', text: 'Drive to Central Serengeti, known for resident Big Five wildlife.' },
      { day: 'Day 3', title: 'Serengeti National Park', text: 'Full day game drive following the Great Migration trails across the Serengeti plains.' },
      { day: 'Day 4', title: 'Serengeti National Park (Kogatende)', text: 'Game drive in the Mara region viewing the Great Migration, with a chance of witnessing a Mara River crossing.' },
      { day: 'Day 5', title: 'Serengeti National Park (North Mara)', text: 'Continue viewing the migration in the far north of the Serengeti. Optional hot air balloon safari available (from $546pp, paid separately).' },
      { day: 'Day 6', title: 'Serengeti – Ngorongoro Conservation Area', text: 'Morning game drive, then transfer to Ngorongoro via the Olduvai Gorge museum and the Laetoli footprints (3.6 million years old).' },
      { day: 'Day 7', title: 'Ngorongoro Crater Tour', text: 'Early morning game drive inside the Ngorongoro Crater.' },
      { day: 'Day 8', title: 'Lake Manyara National Park – Arusha', text: 'Morning game drive at Lake Manyara, then return to Arusha or transfer to the airport for departure.' },
    ],
  },
  {
    id: 7,
    name: '5 Days Selous Game Reserve & Mikumi National Park',
    duration: '5 Days / 4 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/leopard.png',
    highlight: 'Southern Circuit',
    desc: 'Discover the Rufiji River by boat, encounter hippos and crocodiles in the Selous Game Reserve, then spot giraffe, buffalo, elephant, lion and leopard on game drives in Mikumi National Park. Departs from and returns to Dar es Salaam.',
    parks: ['Selous Game Reserve', 'Mikumi National Park'],
    itinerary: [
      { day: 'Day 1', title: 'Dar es Salaam – Selous Game Reserve', text: 'Pickup from your hotel in Dar es Salaam and drive to the Selous, arriving in time for game viewing and an evening boat safari on the Rufiji River.' },
      { day: 'Day 2–3', title: 'Selous Game Reserve', text: 'Two full days exploring the Selous by foot safari, vehicle game drive and Rufiji River boat trips - hippos, crocodiles and around 350 bird species.' },
      { day: 'Day 4', title: 'Selous – Mikumi National Park', text: 'Morning drive across the northern Selous to Mikumi - giraffe, buffalo, elephant, lion, leopard, zebra, wild dog and more, viewed from game drives and observation towers.' },
      { day: 'Day 5', title: 'Mikumi National Park – Dar es Salaam', text: 'Early morning game drive in Mikumi, then return to Dar es Salaam.' },
    ],
  },
  {
    id: 8,
    name: '6 Days Ruaha, Mikumi & Udzungwa National Park',
    duration: '6 Days / 5 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/Lionessrock.png',
    highlight: 'Off the Beaten Path',
    desc: "An off-the-beaten-path southern circuit through Mikumi National Park, the vast and unspoilt Ruaha National Park, and a waterfall hike in the Udzungwa Mountains. Departs from and returns to Dar es Salaam.",
    parks: ['Mikumi National Park', 'Ruaha National Park', 'Udzungwa Mountains'],
    itinerary: [
      { day: 'Day 1', title: 'Dar es Salaam – Mikumi National Park', text: 'Drive to Mikumi with a packed lunch, with game viewing en route - lion, eland, hartebeest, buffalo, wildebeest, giraffe, zebra, elephant and wild dog.' },
      { day: 'Day 2', title: 'Mikumi – Iringa', text: 'Sunrise game drive in Mikumi, then drive to Iringa via the Isimila Stone Age Site.' },
      { day: 'Day 3', title: 'Iringa – Ruaha National Park', text: 'Drive to Ruaha National Park - one of the largest and most unspoilt parks in Africa - with an afternoon game drive.' },
      { day: 'Day 4', title: 'Full Day Ruaha National Park', text: 'A full day of game viewing along the Great Ruaha River - hippo, crocodile, lion, leopard, wild dog, giraffe, elephant, cheetah and more.' },
      { day: 'Day 5', title: 'Ruaha – Udzungwa Mountains National Park', text: 'Early game drive in Ruaha, then drive to the Udzungwa Mountains with a packed lunch.' },
      { day: 'Day 6', title: 'Udzungwa – Dar es Salaam', text: 'Trek to the Sanje Waterfalls (180m, with views over the Kilombero Valley), then drive back to Dar es Salaam.' },
    ],
  },
  {
    id: 9,
    name: '4 Days Zanzibar Kendwa Beach & Stone Town Tour',
    duration: '4 Days / 3 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private tour',
    img: '/images/stone-town.jpg',
    highlight: 'Beach Escape',
    desc: "Combine the history of Zanzibar's UNESCO-listed Stone Town with relaxation on the white sands of Kendwa Beach - a guided city tour, a spice plantation visit, and free time for snorkelling or scuba diving.",
    parks: ['Stone Town (UNESCO)', 'Spice Plantations', 'Kendwa Beach'],
    itinerary: [
      { day: 'Day 1', title: 'Airport Pickup – Stone Town', text: 'Arrive in Zanzibar and transfer to Stone Town, the historic heart of the island.' },
      { day: 'Day 2', title: 'Stone Town & Spice Plantation – Kendwa Beach', text: 'Guided tour of Stone Town - the House of Wonders, the Palace Museum, mosques and the Old Fort and famous carved doors - followed by a spice plantation tour, then drive to Kendwa Beach in the evening.' },
      { day: 'Day 3', title: 'Kendwa Beach', text: 'A free day to relax on the white sands of Kendwa Beach, with the option to go snorkelling or scuba diving.' },
      { day: 'Day 4', title: 'Kendwa Beach – Airport', text: 'Final morning at leisure on the beach before transferring to the airport for your departure.' },
    ],
  },
  {
    id: 10,
    name: '8 Days Tanzania Cultural Tour',
    duration: '8 Days / 7 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Cultural',
    groupLabel: 'Private tour',
    img: '/images/956A1769.jpg',
    highlight: 'Cultural Immersion',
    desc: "Immerse yourself in Tanzania's living cultures - stay with a Maasai community at Olpopongi, visit local schools and historic sites near Tengeru, hike Monduli Mountain, and meet the Hadzabe and Datoga peoples on the shores of Lake Eyasi - before finishing at the Ngorongoro Crater and Olduvai Gorge.",
    parks: ['Olpopongi Maasai Village', 'Monduli', 'Lake Eyasi', 'Ngorongoro & Olduvai Gorge', 'Mto wa Mbu'],
    itinerary: [
      { day: 'Day 1', title: 'Olpopongi Maasai Village', text: 'Arrive at Kilimanjaro International Airport and drive to the Olpopongi Maasai Village on the slopes of West Kilimanjaro, welcomed by the village chief.' },
      { day: 'Day 2', title: 'Olpopongi Maasai Village', text: 'A guided walking safari and bush excursion with Maasai warriors covering medicinal plants, traditional tools and fire-making, followed by an evening of traditional song and dance.' },
      { day: 'Day 3', title: 'Tengeru Cultural Tour – Arusha', text: 'Visit local primary schools, including a school for children with disabilities, and a historic WWII-era stone quarry site, before driving to Arusha for the night.' },
      { day: 'Day 4', title: 'Monduli Juu Cultural Walk', text: 'Drive to Monduli and walk through forest with an armed ranger, summiting Monduli Mountain for views of Kilimanjaro and Mount Meru.' },
      { day: 'Day 5', title: 'Lake Eyasi – Cultural Interaction', text: 'Drive to Lake Eyasi in the Rift Valley to meet the Datoga (Mang\'ati) tribe and explore the landscape with the Hadzabe bushmen.' },
      { day: 'Day 6', title: 'Lake Eyasi – Ngorongoro Conservation Area', text: 'An early morning hunting walk with the Hadzabe, then drive to the Ngorongoro Conservation Area with wildlife viewing en route.' },
      { day: 'Day 7', title: 'Olduvai Gorge & Maasai Village Visit', text: 'Visit a local Maasai village with an optional stop at Olduvai Gorge, the site of major early-human discoveries.' },
      { day: 'Day 8', title: 'Mto wa Mbu Cultural Tour – Arusha', text: 'A community-based cultural tour of Mto wa Mbu - local foods, walking and biking tours - before returning to Arusha.' },
    ],
  },
];
