export const toursTrekking = [
  {
    id: 11,
    slug: 'kilimanjaro-machame-route-7-days',
    name: '7 Days Kilimanjaro Machame Route',
    duration: '7 Days / 6 Nights',
    price: 'From $2,250',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private climb',
    img: '/images/kilimanjaro-graded.jpg',
    highlight: 'The Whiskey Route',
    desc: "Kilimanjaro's most scenic and most popular route. Machame climbs through rainforest onto the Shira Plateau, over the Lava Tower and up the Barranco Wall, following the climb-high, sleep-low profile that gives it one of the best summit success rates on the mountain.",
    parks: ['Kilimanjaro National Park', 'Shira Plateau', 'Barranco Wall', 'Uhuru Peak (5,895m)'],
    itinerary: [
      { day: 'Day 1', title: 'Machame Gate (1,800m) – Machame Camp (3,000m)', text: 'Drive from Moshi to Machame Gate for registration, then hike five to six hours through dense montane rainforest, home to colobus and blue monkeys.', meals: 'Lunch, Dinner', accommodation: 'Mountain camping at Machame Camp.' },
      { day: 'Day 2', title: 'Machame Camp – Shira Cave (3,850m)', text: 'Leave the forest behind and climb through giant heather and moorland onto the Shira Plateau, with the first open views of Kibo and Mount Meru.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Shira Cave Camp.' },
      { day: 'Day 3', title: 'Shira Cave – Lava Tower (4,600m) – Barranco Camp (3,950m)', text: 'The key acclimatisation day: climb to the foot of the Lava Tower for lunch at altitude, then descend into the Barranco Valley among giant groundsels.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Barranco Camp.' },
      { day: 'Day 4', title: 'Barranco Camp – Karanga Camp (4,035m)', text: 'Scramble up the famous Barranco Wall — steep but non-technical — then traverse the southern slopes to Karanga Valley.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Karanga Camp.' },
      { day: 'Day 5', title: 'Karanga Camp – Barafu Camp (4,640m)', text: 'A short morning hike across alpine desert to base camp. Early dinner, a summit briefing, and rest before the midnight start.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Barafu Camp.' },
      { day: 'Day 6', title: 'Summit Day – Uhuru Peak (5,895m) – Mweka Camp (3,100m)', text: 'Set off around midnight to reach Stella Point at sunrise and Uhuru Peak, the roof of Africa, shortly after. Descend to Mweka Camp for a well-earned rest.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Mweka Camp.' },
      { day: 'Day 7', title: 'Mweka Camp – Mweka Gate – Moshi', text: 'A final descent through rainforest to Mweka Gate, where you collect your summit certificate before transferring back to your hotel in Moshi.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 12,
    slug: 'kilimanjaro-lemosho-route-8-days',
    name: '8 Days Kilimanjaro Lemosho Route',
    duration: '8 Days / 7 Nights',
    price: 'From $2,650',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private climb',
    img: '/images/kili.webp',
    highlight: 'Best for Acclimatisation',
    desc: "Our guides' favourite way up. Lemosho starts on the remote western side of the mountain and crosses the full width of the Shira Plateau before joining the southern circuit. It is quieter, with more time to acclimatise, which is why it has the highest summit success of any route we run.",
    parks: ['Kilimanjaro National Park', 'Lemosho Glades', 'Shira Plateau', 'Uhuru Peak (5,895m)'],
    itinerary: [
      { day: 'Day 1', title: 'Londorossi Gate – Mti Mkubwa Camp (2,650m)', text: 'Drive around the mountain to Londorossi Gate, then walk through untouched rainforest to the "Big Tree" camp.', meals: 'Lunch, Dinner', accommodation: 'Mountain camping at Mti Mkubwa.' },
      { day: 'Day 2', title: 'Mti Mkubwa – Shira 1 Camp (3,500m)', text: 'Climb out of the forest into heath and moorland and onto the rim of the Shira Plateau.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Shira 1.' },
      { day: 'Day 3', title: 'Shira 1 – Shira 2 Camp (3,850m)', text: 'An easy crossing of the plateau with Kibo ahead of you the whole way, plus an optional acclimatisation walk.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Shira 2.' },
      { day: 'Day 4', title: 'Shira 2 – Lava Tower (4,600m) – Barranco Camp (3,950m)', text: 'Climb high to the Lava Tower, then drop into the Barranco Valley to sleep low.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Barranco Camp.' },
      { day: 'Day 5', title: 'Barranco Camp – Karanga Camp (4,035m)', text: 'Tackle the Barranco Wall in the morning and traverse to Karanga Valley.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Karanga Camp.' },
      { day: 'Day 6', title: 'Karanga Camp – Barafu Camp (4,640m)', text: 'A short hike to base camp, then rest and prepare for the summit.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Barafu Camp.' },
      { day: 'Day 7', title: 'Summit Day – Uhuru Peak (5,895m) – Mweka Camp (3,100m)', text: 'A midnight start to Stella Point and Uhuru Peak for sunrise over the glaciers, then a long descent to Mweka.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Mweka Camp.' },
      { day: 'Day 8', title: 'Mweka Camp – Mweka Gate – Moshi', text: 'Descend through the forest to the gate for your certificates and transfer back to Moshi.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 13,
    slug: 'kilimanjaro-marangu-route-6-days',
    name: '6 Days Kilimanjaro Marangu Route',
    duration: '6 Days / 5 Nights',
    price: 'From $1,950',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private climb',
    img: '/images/kilimanjaro-graded.jpg',
    highlight: 'Huts, Not Tents',
    desc: "The only route on Kilimanjaro with hut accommodation throughout. Marangu follows a gentle, steady gradient up and down the same path, and this six-day version adds an extra acclimatisation day at Horombo to give you a much better chance at the summit.",
    parks: ['Kilimanjaro National Park', 'Mandara Hut', 'Horombo Hut', 'Uhuru Peak (5,895m)'],
    itinerary: [
      { day: 'Day 1', title: 'Marangu Gate (1,860m) – Mandara Hut (2,700m)', text: 'Register at Marangu Gate and walk through rainforest to Mandara Hut, with an optional detour to the Maundi Crater.', meals: 'Lunch, Dinner', accommodation: 'Mandara Hut (dormitory A-frame huts).' },
      { day: 'Day 2', title: 'Mandara Hut – Horombo Hut (3,720m)', text: 'Emerge from the forest onto open moorland, with Kibo and Mawenzi peaks coming into view.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Horombo Hut.' },
      { day: 'Day 3', title: 'Acclimatisation Day at Horombo', text: 'A walk up to Zebra Rocks or towards the Mawenzi saddle to climb high and sleep low, then back to Horombo.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Horombo Hut.' },
      { day: 'Day 4', title: 'Horombo Hut – Kibo Hut (4,703m)', text: 'Cross the lunar landscape of the saddle between Mawenzi and Kibo to the base of the summit cone.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Kibo Hut.' },
      { day: 'Day 5', title: 'Summit Day – Uhuru Peak (5,895m) – Horombo Hut', text: "Start around midnight up the scree to Gilman's Point, then along the crater rim to Uhuru Peak, before descending all the way to Horombo.", meals: 'Breakfast, Lunch, Dinner', accommodation: 'Horombo Hut.' },
      { day: 'Day 6', title: 'Horombo Hut – Marangu Gate – Moshi', text: 'Descend to the gate to receive your certificates, then transfer back to Moshi.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 14,
    slug: 'kilimanjaro-rongai-route-7-days',
    name: '7 Days Kilimanjaro Rongai Route',
    duration: '7 Days / 6 Nights',
    price: 'From $2,300',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private climb',
    img: '/images/kili.webp',
    highlight: 'The Quiet Northern Approach',
    desc: 'The only route that climbs Kilimanjaro from the north, close to the Kenyan border. Rongai is drier than the southern routes, making it a strong choice in the rainy season, and it is far less crowded. It also includes a night beside Mawenzi Tarn, under the jagged Mawenzi peak.',
    parks: ['Kilimanjaro National Park', 'Mawenzi Tarn', 'Kibo Hut', 'Uhuru Peak (5,895m)'],
    itinerary: [
      { day: 'Day 1', title: 'Rongai Gate (1,950m) – Simba Camp (2,600m)', text: 'Drive to Nale Moru village and walk through pine plantation and forest edge to the first camp.', meals: 'Lunch, Dinner', accommodation: 'Mountain camping at Simba Camp.' },
      { day: 'Day 2', title: 'Simba Camp – Second Cave (3,450m)', text: 'A steady climb onto the moorland with views back over the plains of Kenya.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Second Cave.' },
      { day: 'Day 3', title: 'Second Cave – Kikelewa Camp (3,600m)', text: 'Head towards Mawenzi on a shorter day designed for acclimatisation.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Kikelewa Camp.' },
      { day: 'Day 4', title: 'Kikelewa – Mawenzi Tarn (4,330m)', text: 'A short, steep climb to a glacial lake beneath the spires of Mawenzi, with an afternoon acclimatisation walk.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Mawenzi Tarn.' },
      { day: 'Day 5', title: 'Mawenzi Tarn – Kibo Hut (4,703m)', text: 'Cross the saddle to Kibo Hut, with an early dinner and rest before the summit attempt.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Mountain camping at Kibo.' },
      { day: 'Day 6', title: "Summit Day – Uhuru Peak (5,895m) – Horombo Hut (3,720m)", text: "Climb through the night to Gilman's Point and on to Uhuru Peak, then descend via the Marangu side to Horombo.", meals: 'Breakfast, Lunch, Dinner', accommodation: 'Horombo Hut.' },
      { day: 'Day 7', title: 'Horombo Hut – Marangu Gate – Moshi', text: 'A final descent through the rainforest to Marangu Gate and transfer to Moshi.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 15,
    slug: 'mount-meru-climb-4-days',
    name: '4 Days Mount Meru Climb',
    duration: '4 Days / 3 Nights',
    price: 'From $1,050',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private climb',
    img: '/images/kilimanjaro-graded.jpg',
    highlight: "Kilimanjaro's Wilder Neighbour",
    desc: "Tanzania's second-highest mountain rises out of Arusha National Park, so the walk starts among giraffe, buffalo and colobus monkeys with an armed ranger alongside. The summit ridge above the ash cone is dramatic, and many climbers use Meru to acclimatise before Kilimanjaro.",
    parks: ['Arusha National Park', 'Miriakamba Hut', 'Little Meru', 'Socialist Peak (4,566m)'],
    itinerary: [
      { day: 'Day 1', title: 'Momella Gate (1,500m) – Miriakamba Hut (2,514m)', text: 'Walk with an armed park ranger through open grassland and forest, passing buffalo, giraffe and the famous Fig Tree Arch.', meals: 'Lunch, Dinner', accommodation: 'Miriakamba Hut.' },
      { day: 'Day 2', title: 'Miriakamba Hut – Saddle Hut (3,570m) – Little Meru', text: 'Climb steeply through montane forest to Saddle Hut, with an afternoon hike up Little Meru (3,820m) for sunset over Kilimanjaro.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Saddle Hut.' },
      { day: 'Day 3', title: 'Summit Day – Socialist Peak (4,566m) – Miriakamba Hut', text: 'An early start along the narrow crater rim to reach the summit at sunrise, with Kilimanjaro floating above the clouds, then descend to Miriakamba.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Miriakamba Hut.' },
      { day: 'Day 4', title: 'Miriakamba Hut – Momella Gate – Arusha', text: 'A gentle descent with more wildlife along the way, then transfer back to Arusha.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 16,
    slug: 'ol-doinyo-lengai-lake-natron-3-days',
    name: '3 Days Ol Doinyo Lengai & Lake Natron',
    duration: '3 Days / 2 Nights',
    price: 'From $950',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private trek',
    img: '/images/flamingo.webp',
    highlight: 'Night Climb on an Active Volcano',
    desc: "The Maasai call it the Mountain of God. Ol Doinyo Lengai is the only active volcano in the world that erupts carbonatite lava. You climb it overnight to reach the crater rim at dawn, looking out over Lake Natron and its flamingo flocks in the Rift Valley below.",
    parks: ['Lake Natron', 'Ngare Sero Waterfalls', 'Ol Doinyo Lengai (2,962m)'],
    itinerary: [
      { day: 'Day 1', title: 'Arusha – Lake Natron', text: 'Drive north through Maasai country into the Rift Valley, then take an afternoon walk to the Ngare Sero waterfalls and the flamingo flats of Lake Natron.', meals: 'Lunch, Dinner', accommodation: 'Overnight at a tented camp at Lake Natron.' },
      { day: 'Day 2', title: 'Ol Doinyo Lengai Summit (2,962m)', text: 'Start around midnight for a steep five-to-six-hour climb to the crater rim at sunrise, then descend and rest through the afternoon.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a tented camp at Lake Natron.' },
      { day: 'Day 3', title: 'Lake Natron – Arusha', text: 'An optional Maasai cultural walk in the morning, then drive back to Arusha.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 17,
    slug: 'kilimanjaro-day-hike',
    name: '1 Day Kilimanjaro Day Hike',
    duration: '1 Day',
    price: 'From $260',
    priceNote: 'per person',
    type: 'Trekking',
    groupLabel: 'Private hike',
    img: '/images/kili.webp',
    highlight: 'A Taste of the Mountain',
    desc: "No time for the full climb? Walk through Kilimanjaro's rainforest from Marangu Gate to Mandara Hut and the rim of the Maundi Crater. It is a real day on the mountain, with park fees, a certified guide and a packed lunch included.",
    parks: ['Kilimanjaro National Park', 'Mandara Hut', 'Maundi Crater'],
    itinerary: [
      { day: 'Day 1', title: 'Moshi – Marangu Gate – Mandara Hut – Moshi', text: 'Pickup in Moshi or Arusha, then hike about three hours up through the rainforest to Mandara Hut (2,700m) and the Maundi Crater viewpoint before descending to the gate.', meals: 'Breakfast, Lunch', accommodation: 'Day trip — no overnight.' },
    ],
  },
];
