export const toursBeach = [
  {
    id: 18,
    slug: 'zanzibar-beach-holiday-6-days',
    name: '6 Days Zanzibar Beach Holiday',
    duration: '6 Days / 5 Nights',
    price: 'From $1,150',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private tour',
    img: '/images/px-beach-zanzibar-villa.jpg',
    highlight: 'Island Time',
    desc: "The whole island at an easy pace. You get a night in Stone Town, a spice farm, the red colobus monkeys of Jozani Forest, and then four days on the white-sand east coast at Paje, where the tide goes out for hundreds of metres and kitesurfers fill the lagoon.",
    parks: ['Stone Town (UNESCO)', 'Jozani Forest', 'Spice Plantations', 'Paje Beach'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival – Stone Town', text: 'Airport pickup and transfer to your hotel in Stone Town, with sunset dinner at the Forodhani Gardens night market.', meals: 'Dinner', accommodation: 'Overnight at a boutique hotel in Stone Town.' },
      { day: 'Day 2', title: 'Stone Town Walking Tour – Spice Farm – Paje', text: "Explore the old town's carved doors, Darajani Market and the Old Fort, then visit a spice plantation before driving to the east coast.", meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a beach hotel in Paje.' },
      { day: 'Day 3', title: 'Jozani Forest – Paje', text: "Morning in Jozani Chwaka Bay National Park, home to the endemic Zanzibar red colobus monkey, with the afternoon free on the beach.", meals: 'Breakfast, Dinner', accommodation: 'Overnight at a beach hotel in Paje.' },
      { day: 'Day 4', title: 'Paje Beach', text: 'A free day. Optional kitesurfing lessons, a seaweed farm visit, or a dhow trip to snorkel the reef.', meals: 'Breakfast, Dinner', accommodation: 'Overnight at a beach hotel in Paje.' },
      { day: 'Day 5', title: 'Paje Beach', text: 'Another day at leisure, with an optional trip to The Rock restaurant perched on its own rock in the lagoon.', meals: 'Breakfast, Dinner', accommodation: 'Overnight at a beach hotel in Paje.' },
      { day: 'Day 6', title: 'Paje – Airport', text: 'Final morning on the beach, then transfer to the airport.', meals: 'Breakfast', accommodation: 'End of tour — no overnight.' },
    ],
  },
  {
    id: 19,
    slug: 'safari-and-zanzibar-10-days',
    name: '10 Days Safari & Zanzibar Beach',
    duration: '10 Days / 9 Nights',
    price: 'From $3,850',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private safari & tour',
    img: '/images/px-beach-white-sand.jpg',
    highlight: 'Bush to Beach',
    desc: "The classic Tanzania pairing. You spend five days on the northern circuit (Tarangire, the Serengeti and the Ngorongoro Crater), then take a short flight to Zanzibar and finish with four nights on the powder-white beaches of Nungwi.",
    parks: ['Tarangire', 'Serengeti', 'Ngorongoro Crater', 'Stone Town', 'Nungwi Beach'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Arusha', text: 'Airport pickup and transfer to your lodge for a trip briefing.', meals: 'Dinner', accommodation: 'Overnight at a lodge in Arusha.' },
      { day: 'Day 2', title: 'Tarangire National Park', text: 'Game drive among the baobabs and the big elephant herds along the Tarangire River.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a lodge near Tarangire.' },
      { day: 'Day 3', title: 'Serengeti National Park', text: 'Drive through the Ngorongoro highlands onto the Serengeti plains, with game viewing en route.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a tented camp in the Serengeti.' },
      { day: 'Day 4', title: 'Full Day Serengeti', text: 'A full day following the big cats and, seasonally, the Great Migration.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a tented camp in the Serengeti.' },
      { day: 'Day 5', title: 'Ngorongoro Crater', text: 'Descend into the crater for a game drive among black rhino, lion and flamingos.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a lodge in Karatu.' },
      { day: 'Day 6', title: 'Fly Arusha – Zanzibar', text: 'Morning flight to Zanzibar and an afternoon walking tour of Stone Town.', meals: 'Breakfast, Dinner', accommodation: 'Overnight at a boutique hotel in Stone Town.' },
      { day: 'Day 7', title: 'Spice Farm – Nungwi', text: 'Visit a spice plantation on the way to the northern tip of the island.', meals: 'Breakfast, Dinner', accommodation: 'Overnight at a beach resort in Nungwi.' },
      { day: 'Day 8', title: 'Mnemba Atoll Snorkelling', text: 'A dhow trip to the Mnemba reef to snorkel with turtles and reef fish, often with dolphins on the way.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a beach resort in Nungwi.' },
      { day: 'Day 9', title: 'Nungwi Beach', text: 'A free day, ending with a sunset dhow cruise.', meals: 'Breakfast, Dinner', accommodation: 'Overnight at a beach resort in Nungwi.' },
      { day: 'Day 10', title: 'Nungwi – Airport', text: 'Transfer to Zanzibar airport for your onward flight.', meals: 'Breakfast', accommodation: 'End of tour — no overnight.' },
    ],
  },
  {
    id: 20,
    slug: 'stone-town-prison-island-day-trip',
    name: '1 Day Stone Town & Prison Island',
    duration: '1 Day',
    price: 'From $90',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private tour',
    img: '/images/px-beach-tortoises.jpg',
    highlight: 'Tortoises & Old Town',
    desc: "A guided morning in Stone Town's maze of alleys, then a boat out to Changuu (Prison) Island to meet the giant Aldabra tortoises, some over 150 years old, and to swim off the Nakupenda sandbank.",
    parks: ['Stone Town (UNESCO)', 'Changuu (Prison) Island', 'Nakupenda Sandbank'],
    itinerary: [
      { day: 'Day 1', title: 'Stone Town – Prison Island – Nakupenda', text: 'Walking tour of Stone Town (the Old Fort, House of Wonders, Darajani Market and the former slave market), then a boat to Prison Island and on to Nakupenda sandbank for swimming and a seafood lunch.', meals: 'Lunch', accommodation: 'Day trip — no overnight.' },
    ],
  },
  {
    id: 21,
    slug: 'mnemba-atoll-snorkelling-day-trip',
    name: '1 Day Mnemba Atoll Snorkelling',
    duration: '1 Day',
    price: 'From $120',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private boat',
    img: '/images/px-beach-turtle.jpg',
    highlight: "Zanzibar's Best Reef",
    desc: 'Sail by traditional dhow to the protected reef around Mnemba Atoll, the clearest water around Zanzibar. You can snorkel alongside green turtles and reef fish, and there is a good chance of swimming near wild bottlenose dolphins.',
    parks: ['Mnemba Atoll Marine Reserve', 'Matemwe'],
    itinerary: [
      { day: 'Day 1', title: 'Matemwe – Mnemba Atoll – Matemwe', text: 'Hotel pickup and boat from Matemwe beach to Mnemba for two snorkelling stops, then a fresh seafood lunch on the beach before returning.', meals: 'Lunch', accommodation: 'Day trip — no overnight.' },
    ],
  },
  {
    id: 22,
    slug: 'mafia-island-whale-sharks-4-days',
    name: '4 Days Mafia Island & Whale Sharks',
    duration: '4 Days / 3 Nights',
    price: 'From $1,450',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private tour',
    img: '/images/px-beach-whale-shark.jpg',
    highlight: 'Swim with Whale Sharks',
    desc: "Mafia is the quiet island. There are no big resorts, just one of the Indian Ocean's healthiest marine parks. From October to March, whale sharks gather off Kilindoni, and you can swim beside them in the open water.",
    parks: ['Mafia Island Marine Park', 'Kilindoni', 'Chole Island'],
    itinerary: [
      { day: 'Day 1', title: 'Fly Dar es Salaam – Mafia Island', text: 'A short flight south and transfer to your lodge on Chole Bay.', meals: 'Dinner', accommodation: 'Overnight at a lodge on Chole Bay.' },
      { day: 'Day 2', title: 'Whale Shark Excursion', text: 'Morning boat trip off Kilindoni to swim with whale sharks (seasonal, October to March), then an afternoon at leisure.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a lodge on Chole Bay.' },
      { day: 'Day 3', title: 'Marine Park & Chole Island', text: "Snorkel the coral gardens of the marine park, then explore the 19th-century ruins and giant baobabs on Chole Island.", meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a lodge on Chole Bay.' },
      { day: 'Day 4', title: 'Mafia – Dar es Salaam', text: 'Final swim, then fly back to Dar es Salaam.', meals: 'Breakfast', accommodation: 'End of tour — no overnight.' },
    ],
  },
  {
    id: 23,
    slug: 'pemba-island-escape-5-days',
    name: '5 Days Pemba Island Escape',
    duration: '5 Days / 4 Nights',
    price: 'From $1,350',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private tour',
    img: '/images/px-beach-pemba-canoe.jpg',
    highlight: 'The Green Island',
    desc: "Zanzibar's hilly, clove-scented sister island, and one of the least-visited corners of the coast. Pemba offers some of the best diving in East Africa, the Ngezi rainforest, and Misali Island's untouched reefs.",
    parks: ['Pemba Island', 'Misali Island', 'Ngezi Forest Reserve'],
    itinerary: [
      { day: 'Day 1', title: 'Fly Zanzibar – Pemba', text: 'A short hop north and transfer to your beach lodge.', meals: 'Dinner', accommodation: 'Overnight at a beach lodge on Pemba.' },
      { day: 'Day 2', title: 'Misali Island', text: 'A boat trip to the Misali Island conservation area for snorkelling, nature trails and a beach picnic.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a beach lodge on Pemba.' },
      { day: 'Day 3', title: 'Ngezi Forest & Clove Farms', text: 'Walk through the Ngezi rainforest looking for the Pemba flying fox, and visit a clove plantation.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a beach lodge on Pemba.' },
      { day: 'Day 4', title: 'Pemba at Leisure', text: 'A free day, with optional diving on the Pemba Channel walls.', meals: 'Breakfast, Dinner', accommodation: 'Overnight at a beach lodge on Pemba.' },
      { day: 'Day 5', title: 'Pemba – Zanzibar', text: 'Fly back to Zanzibar for your onward connection.', meals: 'Breakfast', accommodation: 'End of tour — no overnight.' },
    ],
  },
];
