export const toursMore = [
  {
    id: 6,
    slug: 'wildebeest-migration-8-days',
    name: '8 Days Wildebeest Migration River Crossing',
    duration: '8 Days / 7 Nights',
    price: 'From $4,250',
    priceNote: 'per person',
    type: 'Migration',
    groupLabel: 'Private safari',
    img: '/images/956A3311.webp',
    highlight: 'Migration Special',
    desc: 'Follow the Great Migration from Tarangire to the Mara River crossings in the northern Serengeti, with an optional hot air balloon flight (from $546pp), before finishing with the Ngorongoro Crater, Olduvai Gorge and Lake Manyara.',
    parks: ['Tarangire', 'Serengeti (Seronera, Kogatende, North Mara)', 'Ngorongoro', 'Olduvai Gorge & Laetoli', 'Lake Manyara'],
    itinerary: [
      { day: 'Day 1', title: 'Arusha – Tarangire National Park', text: 'Game drive in Tarangire - large elephant herds, tree-climbing lions and the iconic baobab "Tree of Life".', meals: 'Lunch, Dinner', accommodation: 'Overnight at the lodge.' },
      { day: 'Day 2', title: 'Serengeti National Park (Seronera)', text: 'Drive to Central Serengeti, known for resident Big Five wildlife.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the lodge.' },
      { day: 'Day 3', title: 'Serengeti National Park', text: 'Full day game drive following the Great Migration trails across the Serengeti plains.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the lodge.' },
      { day: 'Day 4', title: 'Serengeti National Park (Kogatende)', text: 'Game drive in the Mara region viewing the Great Migration, with a chance of witnessing a Mara River crossing.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the lodge.' },
      { day: 'Day 5', title: 'Serengeti National Park (North Mara)', text: 'Continue viewing the migration in the far north of the Serengeti. Optional hot air balloon safari available (from $546pp, paid separately).', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the lodge.' },
      { day: 'Day 6', title: 'Serengeti – Ngorongoro Conservation Area', text: 'Morning game drive, then transfer to Ngorongoro via the Olduvai Gorge museum and the Laetoli footprints (3.6 million years old).', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the lodge.' },
      { day: 'Day 7', title: 'Ngorongoro Crater Tour', text: 'Early morning game drive inside the Ngorongoro Crater.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the lodge.' },
      { day: 'Day 8', title: 'Lake Manyara National Park – Arusha', text: 'Morning game drive at Lake Manyara, then return to Arusha or transfer to the airport for departure.', meals: 'Breakfast, Lunch', accommodation: 'End of tour — no overnight.' },
    ],
  },
  {
    id: 7,
    slug: 'selous-mikumi-5-days',
    name: '5 Days Selous Game Reserve & Mikumi National Park',
    duration: '5 Days / 4 Nights',
    price: 'From $1,850',
    priceNote: 'per person',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/px-nyerere-hippos.jpg',
    highlight: 'Southern Circuit',
    desc: 'Discover the Rufiji River by boat, encounter hippos and crocodiles in the Selous Game Reserve, then spot giraffe, buffalo, elephant, lion and leopard on game drives in Mikumi National Park. Departs from and returns to Dar es Salaam.',
    parks: ['Nyerere National Park (Selous)', 'Mikumi National Park'],
    itinerary: [
      { day: 'Day 1', title: 'Dar es Salaam – Selous Game Reserve', text: 'Pickup from your hotel in Dar es Salaam and drive to the Selous, arriving in time for game viewing and an evening boat safari on the Rufiji River.', meals: 'Dinner', accommodation: 'Overnight at Hippo Camp.' },
      { day: 'Day 2–3', title: 'Selous Game Reserve', text: 'Two full days exploring the Selous by foot safari, vehicle game drive and Rufiji River boat trips - hippos, crocodiles and around 350 bird species.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at Selous Impala Camp / Rufiji River Camp / Sand Rivers Lodge.' },
      { day: 'Day 4', title: 'Selous – Mikumi National Park', text: 'Morning drive across the northern Selous to Mikumi - giraffe, buffalo, elephant, lion, leopard, zebra, wild dog and more, viewed from game drives and observation towers.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at Mikumi Wildlife Camp / Vuma Hills Camp / Foxes Safari Lodge.' },
      { day: 'Day 5', title: 'Mikumi National Park – Dar es Salaam', text: 'Early morning game drive in Mikumi, then return to Dar es Salaam.', meals: 'Breakfast', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 8,
    slug: 'ruaha-mikumi-udzungwa-6-days',
    name: '6 Days Ruaha, Mikumi & Udzungwa National Park',
    duration: '6 Days / 5 Nights',
    price: 'From $2,450',
    priceNote: 'per person',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/Lionessrock.webp',
    highlight: 'Off the Beaten Path',
    desc: "An off-the-beaten-path southern circuit through Mikumi National Park, the vast and unspoilt Ruaha National Park, and a waterfall hike in the Udzungwa Mountains. Departs from and returns to Dar es Salaam.",
    parks: ['Mikumi National Park', 'Ruaha National Park', 'Udzungwa Mountains'],
    itinerary: [
      { day: 'Day 1', title: 'Dar es Salaam – Mikumi National Park', text: 'Drive to Mikumi with a packed lunch, with game viewing en route - lion, eland, hartebeest, buffalo, wildebeest, giraffe, zebra, elephant and wild dog.', meals: 'Lunch, Dinner', accommodation: 'Dinner and overnight at Genesis Motel.' },
      { day: 'Day 2', title: 'Mikumi – Iringa', text: 'Sunrise game drive in Mikumi, then drive to Iringa via the Isimila Stone Age Site.', meals: 'Breakfast, Dinner', accommodation: 'Dinner and overnight at Isimila Hotel.' },
      { day: 'Day 3', title: 'Iringa – Ruaha National Park', text: 'Drive to Ruaha National Park - one of the largest and most unspoilt parks in Africa - with an afternoon game drive.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at the Bandas.' },
      { day: 'Day 4', title: 'Full Day Ruaha National Park', text: 'A full day of game viewing along the Great Ruaha River - hippo, crocodile, lion, leopard, wild dog, giraffe, elephant, cheetah and more.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'All meals and overnight at the Bandas.' },
      { day: 'Day 5', title: 'Ruaha – Udzungwa Mountains National Park', text: 'Early game drive in Ruaha, then drive to the Udzungwa Mountains with a packed lunch.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Dinner and overnight at Udzungwa Mountain View Lodge.' },
      { day: 'Day 6', title: 'Udzungwa – Dar es Salaam', text: 'Trek to the Sanje Waterfalls (180m, with views over the Kilombero Valley), then drive back to Dar es Salaam.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 9,
    slug: 'zanzibar-kendwa-stone-town-4-days',
    name: '4 Days Zanzibar Kendwa Beach & Stone Town Tour',
    duration: '4 Days / 3 Nights',
    price: 'From $850',
    priceNote: 'per person',
    type: 'Beach & Zanzibar',
    groupLabel: 'Private tour',
    img: '/images/px-beach-kendwa-pier.jpg',
    highlight: 'Beach Escape',
    desc: "Combine the history of Zanzibar's UNESCO-listed Stone Town with relaxation on the white sands of Kendwa Beach - a guided city tour, a spice plantation visit, and free time for snorkelling or scuba diving.",
    parks: ['Stone Town (UNESCO)', 'Spice Plantations', 'Kendwa Beach'],
    itinerary: [
      { day: 'Day 1', title: 'Airport Pickup – Stone Town', text: 'Arrive in Zanzibar and transfer to Stone Town, the historic heart of the island.', meals: 'Breakfast', accommodation: 'Overnight at a hotel in Stone Town.' },
      { day: 'Day 2', title: 'Stone Town & Spice Plantation – Kendwa Beach', text: 'Guided tour of Stone Town - the House of Wonders, the Palace Museum, mosques and the Old Fort and famous carved doors - followed by a spice plantation tour, then drive to Kendwa Beach in the evening.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at Kendwa Beach.' },
      { day: 'Day 3', title: 'Kendwa Beach', text: 'A free day to relax on the white sands of Kendwa Beach, with the option to go snorkelling or scuba diving.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at Kendwa Beach.' },
      { day: 'Day 4', title: 'Kendwa Beach – Airport', text: 'Final morning at leisure on the beach before transferring to the airport for your departure.', meals: 'Breakfast, Lunch', accommodation: 'Can be arranged at an extra cost.' },
    ],
  },
  {
    id: 10,
    slug: 'tanzania-cultural-tour-8-days',
    name: '8 Days Tanzania Cultural Tour',
    duration: '8 Days / 7 Nights',
    price: 'From $1,950',
    priceNote: 'per person',
    type: 'Cultural',
    groupLabel: 'Private tour',
    img: '/images/IMG_2493.webp',
    highlight: 'Cultural Immersion',
    desc: "Immerse yourself in Tanzania's living cultures - stay with a Maasai community at Olpopongi, visit local schools and historic sites near Tengeru, hike Monduli Mountain, and meet the Hadzabe and Datoga peoples on the shores of Lake Eyasi - before finishing at the Ngorongoro Crater and Olduvai Gorge.",
    parks: ['Olpopongi Maasai Village', 'Monduli', 'Lake Eyasi', 'Ngorongoro & Olduvai Gorge', 'Mto wa Mbu'],
    itinerary: [
      { day: 'Day 1', title: 'Olpopongi Maasai Village', text: 'Arrive at Kilimanjaro International Airport and drive to the Olpopongi Maasai Village on the slopes of West Kilimanjaro, welcomed by the village chief.', meals: 'Breakfast', accommodation: 'Overnight at the village (full board).' },
      { day: 'Day 2', title: 'Olpopongi Maasai Village', text: 'A guided walking safari and bush excursion with Maasai warriors covering medicinal plants, traditional tools and fire-making, followed by an evening of traditional song and dance.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at a private Maasai house with traditional beds.' },
      { day: 'Day 3', title: 'Tengeru Cultural Tour – Arusha', text: 'Visit local primary schools, including a school for children with disabilities, and a historic WWII-era stone quarry site, before driving to Arusha for the night.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at Mount Meru Hotel, Arusha (full board).' },
      { day: 'Day 4', title: 'Monduli Juu Cultural Walk', text: 'Drive to Monduli and walk through forest with an armed ranger, summiting Monduli Mountain for views of Kilimanjaro and Mount Meru.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at Enguiki Village.' },
      { day: 'Day 5', title: 'Lake Eyasi – Cultural Interaction', text: 'Drive to Lake Eyasi in the Rift Valley to meet the Datoga (Mang\'ati) tribe and explore the landscape with the Hadzabe bushmen.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at Kisimangeda Tented Lodge.' },
      { day: 'Day 6', title: 'Lake Eyasi – Ngorongoro Conservation Area', text: 'An early morning hunting walk with the Hadzabe, then drive to the Ngorongoro Conservation Area with wildlife viewing en route.', meals: 'Breakfast, Lunch', accommodation: 'Overnight at Ngorongoro Serena Lodge.' },
      { day: 'Day 7', title: 'Olduvai Gorge & Maasai Village Visit', text: 'Visit a local Maasai village with an optional stop at Olduvai Gorge, the site of major early-human discoveries.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'Overnight at Ngorongoro Serena Lodge, on the crater rim.' },
      { day: 'Day 8', title: 'Mto wa Mbu Cultural Tour – Arusha', text: 'A community-based cultural tour of Mto wa Mbu - local foods, walking and biking tours - before returning to Arusha.', meals: 'Breakfast, Lunch, Dinner', accommodation: 'End of tour — no overnight.' },
    ],
  },
];
