export const toursClassic = [
  {
    id: 1,
    name: '1 Day Ngorongoro Crater Safari',
    duration: '1 Day',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Day Trip',
    groupLabel: 'Private safari',
    img: '/images/956A3279.jpg',
    highlight: 'Quick Escape',
    desc: 'A short, action-packed safari for travellers with limited time. Descend 600m into the Ngorongoro Crater for half-day game viewing among lion, elephant, wildebeest, zebra, hyena and buffalo, then visit the soda waters of Lake Magadi to see flamingos and hippos.',
    parks: ['Ngorongoro Crater', 'Lake Magadi'],
    itinerary: [
      { day: 'Day 1', title: 'Arusha – Ngorongoro Crater – Arusha', text: 'Depart Arusha at 5:00am via Mto wa Mbu and Karatu to the Ngorongoro Crater. Descend roughly 600m for a half-day game drive among lion, elephant, wildebeest, zebra, gazelle, hyena and buffalo, then visit Lake Magadi for flamingos and waterbirds before climbing back to the rim and returning to Arusha.' },
    ],
  },
  {
    id: 2,
    name: '3 Days Classic Serengeti Safari',
    duration: '3 Days / 2 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/956A2358.jpg',
    highlight: 'Popular Starter',
    desc: "A perfect introduction to Tanzania's safari country. Spend a full day exploring the endless plains of the Serengeti - home to lion, leopard, cheetah, elephant and, seasonally, the wildebeest migration - before a sunrise visit to the Ngorongoro Crater on your way back.",
    parks: ['Serengeti National Park', 'Ngorongoro Crater'],
    itinerary: [
      { day: 'Day 1', title: 'Arusha – Serengeti National Park', text: 'Pickup from your lodge in Arusha and drive to the Serengeti, with an afternoon game drive on arrival. Dinner and overnight at a lodge.' },
      { day: 'Day 2', title: 'Full Day Serengeti National Park', text: 'A full day game drive across the Serengeti plains - lion, leopard, elephant, cheetah, buffalo, zebra, wildebeest, eland, wild dog and crocodile.' },
      { day: 'Day 3', title: 'Ngorongoro Crater – Arusha', text: 'Early morning drive to Ngorongoro for a crater tour, then return to Arusha by late afternoon.' },
    ],
  },
  {
    id: 3,
    name: '4 Nights / 5 Days Northern Safari',
    duration: '5 Days / 4 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/elephantsafari.png',
    highlight: 'Northern Circuit',
    desc: "The highlights of Tanzania's northern circuit in one trip - Lake Manyara, Serengeti, Ngorongoro Crater and Tarangire - four parks renowned for wildlife density, tree-climbing lions and dramatic scenery.",
    parks: ['Lake Manyara', 'Serengeti', 'Ngorongoro', 'Tarangire'],
    itinerary: [
      { day: 'Day 1', title: 'Arusha – Lake Manyara', text: 'Lunch in Arusha, then drive to Lake Manyara National Park for an evening game drive - hippos, monkeys, tree-climbing lions, flamingos and rich birdlife.' },
      { day: 'Day 2', title: 'Manyara – Serengeti', text: 'Early breakfast and drive to the Serengeti, with afternoon game viewing - wildebeest, zebra, gazelle and lion.' },
      { day: 'Day 3', title: 'Serengeti – Ngorongoro', text: 'Morning game drive in the Serengeti, then transfer to the Ngorongoro Conservation Area for a half-day crater tour.' },
      { day: 'Day 4', title: 'Ngorongoro – Tarangire', text: 'Transfer to Tarangire National Park for an afternoon game drive - lesser kudu, eland, lion, gerenuk and iconic baobab trees.' },
      { day: 'Day 5', title: 'Tarangire – Arusha', text: 'Early morning game drive in Tarangire, then drive back to Arusha with game viewing en route.' },
    ],
  },
  {
    id: 4,
    name: '6 Days Best of Tanzania Safari',
    duration: '6 Days / 5 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/956A3309.jpg',
    highlight: 'Fan Favourite',
    desc: "Tanzania's most famous parks in one circuit - Tarangire, Serengeti, Ngorongoro and Lake Manyara. Offered year-round, this safari can be timed for the wildebeest calving season (December–April) or the Mara River crossings (July–October).",
    parks: ['Tarangire', 'Serengeti', 'Ngorongoro', 'Lake Manyara'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Arusha', text: 'Airport pickup and transfer to your lodge in Arusha for a trip briefing.' },
      { day: 'Day 2', title: 'Tarangire National Park', text: 'Drive to Tarangire - large herds of elephant, tree-climbing lions, baobab trees and the Tarangire River.' },
      { day: 'Day 3', title: 'Serengeti National Park', text: 'Drive to the Serengeti with a picnic lunch and game drive en route, following the Great Migration trails.' },
      { day: 'Day 4', title: 'Serengeti National Park', text: 'A full day game drive in the Serengeti - vast plains, abundant predators, and (seasonally) the wildebeest migration.' },
      { day: 'Day 5', title: 'Ngorongoro Conservation Area', text: "Game drive in the Ngorongoro Crater, the world's largest unbroken volcanic caldera." },
      { day: 'Day 6', title: 'Lake Manyara National Park – Arusha', text: 'Game drive at Lake Manyara - flamingos, pelicans, storks and tree-climbing lions - before returning to Arusha.' },
    ],
  },
  {
    id: 5,
    name: '8 Days Best of Northern Tanzania Safari',
    duration: '8 Days / 7 Nights',
    price: 'On Request',
    priceNote: 'tailored quote',
    type: 'Classic',
    groupLabel: 'Private safari',
    img: '/images/956A2613.jpg',
    highlight: 'In-Depth Safari',
    desc: "An in-depth northern circuit covering Tarangire, the Ngorongoro Crater, Olduvai Gorge, three days in the Serengeti, and Lake Manyara. An optional hot air balloon safari over the Serengeti plains is available as an add-on (from $546 per person).",
    parks: ['Tarangire', 'Ngorongoro', 'Olduvai Gorge', 'Serengeti', 'Lake Manyara'],
    itinerary: [
      { day: 'Day 1', title: 'Arrival in Arusha', text: 'Airport pickup and transfer to your lodge in Arusha for a trip briefing.' },
      { day: 'Day 2', title: 'Tarangire National Park', text: 'Afternoon game drive among baobabs and acacia parkland - elephant, lion, leopard and seasonal migration of wildebeest, zebra, eland and oryx.' },
      { day: 'Day 3', title: 'Ngorongoro Conservation Area', text: 'Descend roughly 600m into the Ngorongoro Crater for an afternoon game drive - lion, elephant, rhino, buffalo and abundant plains game.' },
      { day: 'Day 4–6', title: 'Serengeti National Park', text: 'Three days exploring the Serengeti via Olduvai Gorge - over 35 species of plains game, predators including lion, cheetah, wild dog and hyena, and (seasonally) the Great Migration. Optional hot air balloon safari available (from $546pp, paid separately).' },
      { day: 'Day 7', title: 'Serengeti – Karatu', text: 'Morning game drive in the Serengeti, then drive to Karatu for the night.' },
      { day: 'Day 8', title: 'Lake Manyara National Park – Arusha', text: 'Morning game drive at Lake Manyara - Big Five territory and famous tree-climbing lions - before returning to Arusha.' },
    ],
  },
];
